name: Run UI Tests

on:
  workflow_dispatch:
    inputs:
      marker:
        description: "Test marker to run specific tests"
        required: false
        default: "regression"

  pull_request:
    branches:
      - "**" # Run on pull requests for all branches

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies using Poetry
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      # Set environment variables from GitHub Secrets
      - name: Set environment variables
        run: echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

      # Run pytest with the provided marker or regression
      - name: Run tests
        env:
          PASSWORD: ${{ secrets.PASSWORD }}  # Pass the secret to the test environment
        run: |
          marker="${{ github.event.inputs.marker }}"
          if [ -z "$marker" ]; then
            marker="regression"
          fi
          echo "Running tests with marker: $marker"
          poetry run make test "MARKER=$marker"


      # Step 5: Generate Allure HTML report using Makefile
      - name: Generate Allure Report
        run: |
          poetry run make generate-report

      # Step 6: Upload Allure Report as an artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ui_automation_suite/bdd_tests/reports/allure-report-bdd

      # Step 7: Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ui_automation_suite/bdd_tests/reports/allure-report-bdd
